EMOTION_MAP = {
    "anger": "anger",
    "fear": "sadness",
    "joy": "joy",
    "sadness": "sadness",
    "analytical": "neutral",
    "confident": "neutral",
    "tentative": "neutral",
}

# Normalize tones that are less useful as tags for songs.
SONG_TAG_MAP = {
    "anger": "rock",
    "sadness": "acoustic",
    "joy": "pop",
    "neutral": "chill",
}

# Offline-safe recommendations shown when Last.fm is unavailable.
FALLBACK_SONGS_BY_TAG = {
    "pop": [
        {"name": "Blinding Lights", "artist": "The Weeknd"},
        {"name": "Levitating", "artist": "Dua Lipa"},
        {"name": "Can't Stop the Feeling!", "artist": "Justin Timberlake"},
        {"name": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars"},
        {"name": "Shake It Off", "artist": "Taylor Swift"},
        {"name": "As It Was", "artist": "Harry Styles"},
        {"name": "Bad Guy", "artist": "Billie Eilish"},
        {"name": "Firework", "artist": "Katy Perry"},
        {"name": "Happy", "artist": "Pharrell Williams"},
        {"name": "Shape of You", "artist": "Ed Sheeran"},
        {"name": "Roar", "artist": "Katy Perry"},
        {"name": "Sorry", "artist": "Justin Bieber"},
        {"name": "Hips Don't Lie", "artist": "Shakira"},
        {"name": "Call Me Maybe", "artist": "Carly Rae Jepsen"},
        {"name": "Teenage Dream", "artist": "Katy Perry"},
        {"name": "Wake Me Up", "artist": "Avicii"},
        {"name": "Counting Stars", "artist": "OneRepublic"},
        {"name": "Senorita", "artist": "Shawn Mendes"},
        {"name": "Havana", "artist": "Camila Cabello"},
        {"name": "Watermelon Sugar", "artist": "Harry Styles"},
        {"name": "Don't Start Now", "artist": "Dua Lipa"},
        {"name": "Dynamite", "artist": "BTS"},
        {"name": "Anti-Hero", "artist": "Taylor Swift"},
        {"name": "Flowers", "artist": "Miley Cyrus"},
        {"name": "Stay", "artist": "The Kid LAROI"},
    ],
    "acoustic": [
        {"name": "Let Her Go", "artist": "Passenger"},
        {"name": "Skinny Love", "artist": "Bon Iver"},
        {"name": "The A Team", "artist": "Ed Sheeran"},
        {"name": "Fast Car", "artist": "Tracy Chapman"},
        {"name": "Photograph", "artist": "Ed Sheeran"},
        {"name": "Ho Hey", "artist": "The Lumineers"},
        {"name": "Someone Like You", "artist": "Adele"},
        {"name": "Say You Won't Let Go", "artist": "James Arthur"},
        {"name": "Riptide", "artist": "Vance Joy"},
        {"name": "Budapest", "artist": "George Ezra"},
        {"name": "Banana Pancakes", "artist": "Jack Johnson"},
        {"name": "Better Together", "artist": "Jack Johnson"},
        {"name": "I See Fire", "artist": "Ed Sheeran"},
        {"name": "Fix You", "artist": "Coldplay"},
        {"name": "Hallelujah", "artist": "Jeff Buckley"},
        {"name": "Take Me Home Country Roads", "artist": "John Denver"},
        {"name": "Landslide", "artist": "Fleetwood Mac"},
        {"name": "Blackbird", "artist": "The Beatles"},
        {"name": "Tenerife Sea", "artist": "Ed Sheeran"},
        {"name": "Thinking Out Loud", "artist": "Ed Sheeran"},
        {"name": "Gravity", "artist": "John Mayer"},
        {"name": "Heartbeats", "artist": "Jose Gonzalez"},
        {"name": "Home", "artist": "Edward Sharpe and the Magnetic Zeros"},
        {"name": "Chasing Cars", "artist": "Snow Patrol"},
        {"name": "Iris", "artist": "Goo Goo Dolls"},
    ],
    "rock": [
        {"name": "Believer", "artist": "Imagine Dragons"},
        {"name": "Numb", "artist": "Linkin Park"},
        {"name": "Smells Like Teen Spirit", "artist": "Nirvana"},
        {"name": "Boulevard of Broken Dreams", "artist": "Green Day"},
        {"name": "Seven Nation Army", "artist": "The White Stripes"},
        {"name": "Paint It Black", "artist": "The Rolling Stones"},
        {"name": "In The End", "artist": "Linkin Park"},
        {"name": "Thunderstruck", "artist": "AC/DC"},
        {"name": "Back In Black", "artist": "AC/DC"},
        {"name": "Sweet Child O Mine", "artist": "Guns N Roses"},
        {"name": "Hotel California", "artist": "Eagles"},
        {"name": "Livin On A Prayer", "artist": "Bon Jovi"},
        {"name": "Eye of the Tiger", "artist": "Survivor"},
        {"name": "We Will Rock You", "artist": "Queen"},
        {"name": "Bohemian Rhapsody", "artist": "Queen"},
        {"name": "Zombie", "artist": "The Cranberries"},
        {"name": "Radioactive", "artist": "Imagine Dragons"},
        {"name": "Highway to Hell", "artist": "AC/DC"},
        {"name": "Californication", "artist": "Red Hot Chili Peppers"},
        {"name": "The Pretender", "artist": "Foo Fighters"},
        {"name": "Creep", "artist": "Radiohead"},
        {"name": "Mr Brightside", "artist": "The Killers"},
        {"name": "Use Somebody", "artist": "Kings of Leon"},
        {"name": "Dream On", "artist": "Aerosmith"},
        {"name": "Wonderwall", "artist": "Oasis"},
    ],
    "chill": [
        {"name": "Sunset Lover", "artist": "Petit Biscuit"},
        {"name": "Weightless", "artist": "Marconi Union"},
        {"name": "Ocean Eyes", "artist": "Billie Eilish"},
        {"name": "Lovely", "artist": "Billie Eilish & Khalid"},
        {"name": "Golden Hour", "artist": "JVKE"},
        {"name": "Midnight City", "artist": "M83"},
        {"name": "Intro", "artist": "The xx"},
        {"name": "Awake", "artist": "Tycho"},
        {"name": "Night Owl", "artist": "Galimatias"},
        {"name": "Holocene", "artist": "Bon Iver"},
        {"name": "Space Song", "artist": "Beach House"},
        {"name": "Breathe", "artist": "Telepopmusik"},
        {"name": "River Flows In You", "artist": "Yiruma"},
        {"name": "Experience", "artist": "Ludovico Einaudi"},
        {"name": "A Moment Apart", "artist": "ODESZA"},
        {"name": "Bloom", "artist": "ODESZA"},
        {"name": "Open", "artist": "Rhye"},
        {"name": "Teardrop", "artist": "Massive Attack"},
        {"name": "Roads", "artist": "Portishead"},
        {"name": "After Dark", "artist": "Mr Kitty"},
        {"name": "Sun Models", "artist": "ODESZA"},
        {"name": "Anchor", "artist": "Novo Amor"},
        {"name": "Youth", "artist": "Daughter"},
        {"name": "Nothings Gonna Hurt You Baby", "artist": "Cigarettes After Sex"},
        {"name": "Cold Little Heart", "artist": "Michael Kiwanuka"},
    ],
}
